version: '3.3'
services: 
  app:
    image: nexus.devops.ifrn.edu.br/{{ repository|lower }}:latest
    restart: always
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '{{ port }}:80'
